import type { Metadata } from "next";
import "./globals.css";
import contentfuClient from "@/app/lib/contentfulClient";
import MlNavbar, { MlNavbarProps } from '@/components/molecules/MlNavbar'
import { cleanContentfulEntry } from "@/utils/contentful";




export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const getNavbar = async () => {
  const navbars = await contentfuClient.getEntries({
    content_type: "navbar",
  });
  return cleanContentfulEntry<MlNavbarProps>(navbars.items[0]);
};


export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {

  const navbar =  await getNavbar()


  return (
    <html lang="en">
      <body >
      
      <MlNavbar {...navbar} /> 
        {children}
      </body>
    </html>
  );
}
