import type { Metadata } from "next";
import "./globals.css";
import contentfuClient from "@/app/lib/contentfulClient";
import { OrNavbarProps } from "@/components/organism/OrNavbar";
import { cleanContentfulEntry } from "@/utils/contentful";

import type { AutocompleteConnectorParams } from "instantsearch.js/es/connectors/autocomplete/connectAutocomplete";

import { AlgoliaProcutSearch } from "./components/AlgoliaProductsSearch";
import { OrFooter, OrFooterProps } from "@/components/organism/OrFooter";
import { ProductsStoreProvider } from "@/providers/products-store-provider";
import { SiteNavbar } from "@/components/SiteNavbar";

export type UseAutocompleteProps = AutocompleteConnectorParams;

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const getNavbar = async () => {
  const navbars = await contentfuClient.getEntries({
    content_type: "navbar",
  });
  return cleanContentfulEntry<OrNavbarProps>(navbars.items[0]);
};

const getFooter = async () => {
  const footers = await contentfuClient.getEntries({
    content_type: "footer",
    limit: 1,
    include: 8,
  });

  return footers.items && footers.items.length
    ? cleanContentfulEntry<OrFooterProps>(footers.items[0])
    : null;
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const navbar = await getNavbar();
  const footer = await getFooter();
  return (
    <html lang="en">
      <body>
        <ProductsStoreProvider>
          {/* <OrNavbar {...navbar} search={<AlgoliaProcutSearch />} /> */}

          <SiteNavbar navbar={{ ...navbar, search: <AlgoliaProcutSearch /> }} />

          <main className="md:mx-auto pt-42 min-h-screen ">{children}</main>
        </ProductsStoreProvider>

        {footer && <OrFooter {...footer}></OrFooter>}
      </body>
    </html>
  );
}
