import type { Metadata } from "next";
import "./globals.css";
import contentfuClient from "@/app/lib/contentfulClient";
import OrNavbar, { OrNavbarProps } from "@/components/organism/OrNavbar";
import { cleanContentfulEntry } from "@/utils/contentful";

import type { AutocompleteConnectorParams } from "instantsearch.js/es/connectors/autocomplete/connectAutocomplete";

import { AlgoliaProcutSearch } from "./components/AlgoliaProductsSearch";

export type UseAutocompleteProps = AutocompleteConnectorParams;

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const getNavbar = async () => {
  const navbars = await contentfuClient.getEntries({
    content_type: "navbar",
  });
  return cleanContentfulEntry<OrNavbarProps>(navbars.items[0]);
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const navbar = await getNavbar();

  return (
    <html lang="en">
      <body>
        <OrNavbar {...navbar} search={<AlgoliaProcutSearch />} />
        <main className="container px-4 md:mx-auto pt-42 h-[calc(100vh-144px)]">
          {children}
        </main>
      </body>
    </html>
  );
}
